AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - "examples/**/*"
    - "vendor/**/*"

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
